import net.ornithemc.keratin.api.task.build.BuildMappingsJarTask
import net.ornithemc.keratin.api.task.mapping.ConvertMappingsFromTinyV1ToTinyV2Task
import net.ornithemc.keratin.api.task.mapping.GenerateNewIntermediaryTask
import net.ornithemc.keratin.api.task.mapping.UpdateIntermediaryTask

plugins {
	id 'java'
	id 'maven-publish'
	id 'keratin' version '2.1'
}

def ENV = System.getenv()

keratin {
	minecraftVersion = ENV.MC_VERSION ?: 'b1.0'
	intermediaryGen = 2
}

def maven_group = 'net.ornithemc'
def artifact_id = "calamus-intermediary-gen${keratin.intermediaryGen.get()}"

def xml = new URL("https://maven.ornithemc.net/releases/${maven_group.replace('.', '/')}/${artifact_id}/maven-metadata.xml").text
def metadata = new XmlSlurper().parseText(xml)
def publishedVersions = metadata.versioning.versions.version*.text()

def localMappingsPath = "$buildDir/mappings"
new File(localMappingsPath).mkdirs()
keratin.files.mappingsDirectory.eachFile {
	if (!it.name.endsWith(".tiny")) {
		return
	}

	def mcVer = it.name.replace(".tiny", "")

	if (publishedVersions != null && publishedVersions.contains(mcVer)) {
		return
	}

	File tinyV1File = it
	File tinyV2File = new File("$localMappingsPath/${it.name}")

	def conversionTask = "convert${it.name}ToV2"
	tasks.register(name: conversionTask, type: ConvertMappingsFromTinyV1ToTinyV2Task) {
		input = tinyV1File
		output = tinyV2File
	}

	Jar makeV1Jar = task("${mcVer}_buildMappingsJar", type: BuildMappingsJarTask) {
		archiveFileName = "calamus-intermediary-gen${keratin.intermediaryGen.get()}-${mcVer}.jar"
		mappings tinyV1File
	}
	Jar makeV2Jar = task("${mcVer}_buildMappingsJar", type: BuildMappingsJarTask, dependsOn: conversionTask) {
		archiveFileName = "calamus-intermediary-gen${keratin.intermediaryGen.get()}-${mcVer}-v2.jar"
		mappings tinyV2File
	}

	build.dependsOn makeV1Jar
	build.dependsOn makeV2Jar

	publishing {
		publications {
			create("${mcVer}_mavenJava", MavenPublication) {
				groupId maven_group
				artifactId artifact_id
				version mcVer
				artifact(makeV1Jar)
				artifact(makeV2Jar) {
					classifier = 'v2'
				}
			}
		}
	}
}

publishing {
	repositories {
		if (ENV.MAVEN_URL) {
			maven {
				url ENV.MAVEN_URL
				credentials {
					username ENV.MAVEN_USERNAME
					password ENV.MAVEN_PASSWORD
				}
				authentication {
					basic(BasicAuthentication)
				}
			}
		}
	}
}
