import net.ornithemc.keratin.api.TaskSelection
import net.ornithemc.keratin.api.task.mapping.UpdateIntermediaryTask

plugins {
	id 'java'
	id 'maven-publish'
	id 'keratin' version '21.2'
}

def ENV = System.getenv()

keratin {
	if (ENV.MC_VERSION) {
		minecraftVersions ENV.MC_VERSION
	}
	intermediaryGen = 2

	tasks TaskSelection.CALAMUS
}

updateIntermediary {
	if (ENV.FROM_MC_VERSIONS) {
		fromMinecraftVersions ENV.FROM_MC_VERSIONS.split('[,]')
	}
}

publishing {
	repositories {
		if (ENV.MAVEN_URL) {
			maven {
				url ENV.MAVEN_URL
				credentials {
					username ENV.MAVEN_USERNAME
					password ENV.MAVEN_PASSWORD
				}
				authentication {
					basic(BasicAuthentication)
				}
			}
		}
	}
}
