name: publish
on: [workflow_dispatch] # Manual trigger
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: openjdk:17-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - run: ./gradlew publish --stacktrace
        env:
          MAVEN_URL: ${{ secrets.NEW_MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.NEW_MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEW_MAVEN_PASSWORD }}
